

CREATE TABLE HK_ACHIEVE_GOLD (
  HK_ACHIEVE_GOLD_ID int IDENTITY(1,1) PRIMARY KEY,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  VITALITY_STATUS VARCHAR(25) NULL,
  POINTS_BALANCE VARCHAR(25) NULL,
  GENDER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL);
  
  CREATE TABLE HK_ACHIEVE_SILVER (
  HK_ACHIEVE_SILVER_ID int IDENTITY(1,1) PRIMARY KEY,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  VITALITY_STATUS VARCHAR(25) NULL,
  POINTS_BALANCE VARCHAR(25) NULL,
  GENDER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL);
  
  CREATE TABLE HK_ACHIEVE_PLATINUM (
  HK_ACHIEVE_PLATINUM_ID int IDENTITY(1,1) PRIMARY KEY,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  VITALITY_STATUS VARCHAR(25) NULL,
  POINTS_BALANCE VARCHAR(25) NULL,
  GENDER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL);
  
  CREATE TABLE HK_ENGAGEMENT_REMINDER1 (
  HK_ENGAGEMENT_REMINDER1_ID int IDENTITY(1,1) PRIMARY KEY,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL);
  
  CREATE TABLE HK_ENGAGEMENT_REMINDER2 (
  HK_ENGAGEMENT_REMINDER2_ID int IDENTITY(1,1) PRIMARY KEY,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL);
  
  CREATE TABLE HK_ENGAGEMENT_REMINDER3 (
  HK_ENGAGEMENT_REMINDER3_ID int IDENTITY(1,1) PRIMARY KEY,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL);
  
  
  CREATE TABLE PROCESSED_FILE (
  FILE_ID int IDENTITY(1,1) PRIMARY KEY,
  FILE_NAME VARCHAR(255) NULL,
  PROCESS_DATE DATE NULL,
  ELOQUA_PROCESS_DATE DATE NULL,
  DUPLICATE_RECORDS int,
  TOTAL_RECORDS int);
  
  
  CREATE TABLE ELOQUA (
  ID int IDENTITY(1,1) PRIMARY KEY,
  SITE VARCHAR(70) NULL,
  USER_NAME VARCHAR(70) NULL,
  PASS_WORD VARCHAR(70) NULL,
  BASE_URL VARCHAR(70) NULL,
  MODIFIED_BY VARCHAR(70) NULL);
  
  CREATE TABLE FTP (
  ID int IDENTITY(1,1) PRIMARY KEY,
  HOST VARCHAR(70) NULL,
  USER_NAME VARCHAR(70) NULL,
  PASS_WORD VARCHAR(70) NULL,
  MODIFIED_BY VARCHAR(70) NULL);
  
   
  CREATE TABLE CUSTOM_OBJECT_ID (
  ID int IDENTITY(1,1) PRIMARY KEY,
  FILE_TYPE VARCHAR(70) NULL,
  CUSTOME_ID VARCHAR(70) NULL);
  
  CREATE TABLE CUSTOM_FIELD (
  ID int IDENTITY(1,1) PRIMARY KEY,
  FILE_TYPE VARCHAR(70) NULL,
  FIELD_NAME VARCHAR(70) NULL,
  FIELD_ID VARCHAR(70) NULL);
  
  
 insert into ELOQUA (SITE, USER_NAME, PASS_WORD, BASE_URL, MODIFIED_BY) values ('AIA', 'Ramya.Ponnusamy', 'Verticurl2014!', 'https://secure.eloqua.com/API', 'SCRIPT');
 insert into FTP (HOST, USER_NAME, PASS_WORD, MODIFIED_BY) values ('0343825.netsolhost.com', 'verticurl_aia', 'Passw0rd2015', 'SCRIPT');
  
 insert into CUSTOM_OBJECT_ID (FILE_TYPE, CUSTOME_ID) values ('HKAG','15');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'LANGUAGE_PREFERENCE1', '367');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'CLIENT_ID1', '368');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'GENDER1', '369');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'POINTS_BALANCE1', '370');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'VITALITY_STATUS1', '371');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'ENTITY_REFERENCE_NUMBER1', '372');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'AIA_VITALITY_MEMBER_NUMBER1', '373');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'EMAIL_ADDRESS1', '374');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'MEMBER_SURNAME1', '375');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAG', 'MEMBER_FIRST_NAMES1', '376');
 
 insert into CUSTOM_OBJECT_ID (FILE_TYPE, CUSTOME_ID) values ('HKAS','17');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'LANGUAGE_PREFERENCE1', '388');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'CLIENT_ID1', '389');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'GENDER1', '390');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'POINTS_BALANCE1', '391');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'VITALITY_STATUS1', '392');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'ENTITY_REFERENCE_NUMBER1', '393');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'AIA_VITALITY_MEMBER_NUMBER1', '394');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'EMAIL_ADDRESS1', '395');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'MEMBER_SURNAME1', '396');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAS', 'MEMBER_FIRST_NAMES1', '397');
 
  insert into CUSTOM_OBJECT_ID (FILE_TYPE, CUSTOME_ID) values ('HKAP','18');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'LANGUAGE_PREFERENCE1', '398');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'CLIENT_ID1', '399');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'GENDER1', '400');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'POINTS_BALANCE1', '401');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'VITALITY_STATUS1', '402');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'ENTITY_REFERENCE_NUMBER1', '403');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'AIA_VITALITY_MEMBER_NUMBER1', '404');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'EMAIL_ADDRESS1', '405');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'MEMBER_SURNAME1', '406');
 insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKAP', 'MEMBER_FIRST_NAMES1', '407');
 
insert into CUSTOM_OBJECT_ID (FILE_TYPE, CUSTOME_ID) values ('HKER1','24');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'LANGUAGE_PREFERENCE1', '467');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'CLIENT_ID1', '468');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'ENTITY_REFERENCE_NUMBER1', '469');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'AIA_VITALITY_MEMBER_NUMBER1', '470');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'EMAIL_ADDRESS1', '471');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'MEMBER_SURNAME1', '472');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER1', 'MEMBER_FIRST_NAMES1', '473');
 
insert into CUSTOM_OBJECT_ID (FILE_TYPE, CUSTOME_ID) values ('HKER2','25');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'LANGUAGE_PREFERENCE1', '474');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'CLIENT_ID1', '475');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'ENTITY_REFERENCE_NUMBER1', '476');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'AIA_VITALITY_MEMBER_NUMBER1', '477');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'EMAIL_ADDRESS1', '478');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'MEMBER_SURNAME1', '479');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER2', 'MEMBER_FIRST_NAMES1', '480');
 
insert into CUSTOM_OBJECT_ID (FILE_TYPE, CUSTOME_ID) values ('HKER3','26');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'LANGUAGE_PREFERENCE1', '481');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'CLIENT_ID1', '482');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'ENTITY_REFERENCE_NUMBER1', '483');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'AIA_VITALITY_MEMBER_NUMBER1', '484');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'EMAIL_ADDRESS1', '485');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'MEMBER_SURNAME1', '486');
insert into CUSTOM_FIELD (FILE_TYPE,  FIELD_NAME, FIELD_ID) values ('HKER3', 'MEMBER_FIRST_NAMES1', '487');