--run For mysql
CREATE TABLE HK_ACHIEVE_GOLD (
  HK_ACHIEVE_GOLD_ID INTEGER(11) NOT NULL AUTO_INCREMENT,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(70) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  VITALITY_STATUS VARCHAR(25) NULL,
  POINTS_BALANCE VARCHAR(25) NULL,
  GENDER VARCHAR(25) NULL,
  CLIENT_ID VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID VARCHAR(25) NULL,
  FILE_TYPE VARCHAR(25) NULL,
  LAST_MODIFIED_DATE DATE NULL,
  FILE_NAME VARCHAR(255) NULL,
  PRIMARY KEY(HK_ACHIEVE_GOLD_ID));
  
  
  CREATE TABLE PROCESSED_FILE (
  FILE_ID INTEGER(11) NOT NULL AUTO_INCREMENT,
  FILE_NAME VARCHAR(255) NULL,
  PROCESS_DATE DATE NULL,
  ELOQUA_PROCESS_DATE DATE NULL,
  DUPLICATE_RECORDS INTEGER(11),
  TOTAL_RECORDS INTEGER(11),
  PRIMARY KEY(FILE_ID));